global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'your-node-app'
    static_configs:
      - targets: ['host.docker.internal:5000']   # If metrics exposed on port 5000 on host
