name: CI - Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    # Start MongoDB as a service inside the workflow VM
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔨 Build Docker image
        run: docker build -t backend-app ./backend

      - name: ▶️ Run Docker container connected to MongoDB service
        run: |
          docker run -d --rm --network=host --name backend \
          -e PORT=5000 \
          -e MONGO_URI=mongodb://localhost:27017 \
          backend-app
        env:
          # This environment variable makes host.docker.internal resolve correctly inside Docker on GitHub Actions
          DOCKER_HOST_IP: host.docker.internal

      - name: 🧪 Health check the backend
        run: |
          echo "⏳ Waiting for the server..."
          for i in {1..10}; do
            curl --fail http://localhost:5000/health && break
            echo "Retrying ($i)..."
            sleep 3
          done

      - name: 📄 Print Docker logs
        run: docker logs backend || true

      - name: 🧹 Clean up Docker container
        run: |
          docker stop backend || true
          docker rm backend || true
