name: CI - Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    # Start MongoDB as a service inside the workflow VM
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔨 Build Docker image
        run: docker build -t backend-app ./backend

      - name: ▶️ Run Docker container connected to MongoDB service
        run: |
          docker run -d --rm -p 5000:5000 --name backend \
            -e PORT=5000 \
            -e MONGO_URI=mongodb://host.docker.internal:27017 \
            backend-app
        env:
          # This environment variable makes host.docker.internal resolve correctly inside Docker on GitHub Actions
          DOCKER_HOST_IP: host.docker.internal

      - name: 🧪 Health check the backend
        run: |
          sleep 10 # give backend time to start and connect to MongoDB
          curl --fail http://localhost:5000 || (echo "Health check failed" && exit 1)

      - name: 🧹 Clean up Docker container
        run: |
          docker stop backend || true
          docker rm backend || true
